apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webserver
  labels:
    app: willow  
spec:
  replicas: 8
  selector:
    matchLabels:
      app: willow
  template:
    metadata:
      labels:
        app: willow
    spec:
      containers:
        - name: willow-server
          image: kubernetesregistrysangra.azurecr.io/sangra:v2
          ports:
          - containerPort: 80
            name: www
---
    apiVersion: v1
    kind: Service
    metadata:
        name: webserver-front
    spec:
        type: LoadBalancer
        ports:
        - port: 80
        selector:
         app: willow