rg_name             = "SandrosLab"
location            = "westeurope"
jumphost_address    = "193.34.170.35/32"
admin_user          = "adminuser"
filename_public_key = "Public key source"
linux_distro        = "18.04-LTS"